gazebo:
  delay: 0.009
  imus:
    base_imu:
      frame_id: imu_link
      orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
      angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
      linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
  contacts: [ "left_sole_1_link", "left_sole_2_link", "right_sole_1_link", "right_sole_2_link" ]
